#!/bin/bash

export extensions=(
  PeterJausovec.vscode-docker
Unity.unity-debug
eamodio.gitlens
eppz.eppz-code
haaaad.ansible
lukehoban.Go
ms-python.python
ms-vscode.csharp
rebornix.Ruby
wholroyd.jinja
)
